application: go-talks-kwmt
version: 2
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: present/static/favicon.ico
  upload: present/static/favicon.ico
- url: /static
  static_dir: present/static
- url: /.*
  script: _go_app

#skip_files: ^(?!(present|code.google.com)/)
nobuild_files: ^(?!(present|code.google.com)/)

